version: '3.8'

services:
  odoo-postgres:
    hostname: odoo-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network
    ports:
      - published: 5432
        target: 5432
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo-server:
    hostname: odoo-server
    image: odoo:18
    environment:
      - HOST=odoo-postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo123
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_config:/etc/odoo
    networks:
      - odoo-network
    ports:
      - published: 8069
        target: 8069
        protocol: tcp
      - published: 8072
        target: 8072
        protocol: tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - odoo-postgres

  odoo-pgadmin:
    hostname: odoo-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret123!
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_ENHANCED_COOKIES_ENABLED=False
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - odoo-network
    ports:
      - published: 5050
        target: 80
        protocol: tcp
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - odoo-postgres

volumes:
  postgres_data:
    driver: local
    name: odoo_postgres_data
  odoo_data:
    driver: local
    name: odoo_app_data
  odoo_config:
    driver: local
    name: odoo_config_data
  pgadmin_data:
    driver: local
    name: pgadmin_config_data

networks:
  odoo-network:
    driver: overlay
    name: odoo-network
    attachable: true