version: '3.8'

services:
  odoo-postgres:
    container_name: odoo-postgres
    hostname: odoo-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo-server:
    container_name: odoo-server
    hostname: odoo-server
    image: odoo:18
    depends_on:
      - odoo-postgres
    ports:
      - target: 8069
        published: 8069
        protocol: tcp
      - target: 8072
        published: 8072
        protocol: tcp
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_config:/etc/odoo
    environment:
      - HOST=odoo-postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo123
    networks:
      - odoo-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  odoo-pgadmin:
    container_name: odoo-pgadmin
    hostname: odoo-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret123!
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_ENHANCED_COOKIES_ENABLED=False
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
    ports:
      - target: 80
        published: 5050
        protocol: tcp
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - odoo-network
    depends_on:
      - odoo-postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
    driver: local
    name: postgres_data
  odoo_data:
    driver: local
    name: odoo_data
  odoo_config:
    driver: local
    name: odoo_config
  pgadmin_data:
    driver: local
    name: pgadmin_data

networks:
  odoo-network:
    driver: overlay
    name: odoo-network
    attachable: true
