version: '3'

services:
  odoo-postgres:
    hostname: odoo-postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo-server:
    hostname: odoo-server
    image: odoo:18
    restart: always
    depends_on:
      - odoo-postgres
    environment:
      - HOST=odoo-postgres
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo123
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_config:/etc/odoo
    networks:
      - odoo-network
    ports:
      - "8069:8069"
      - "8072:8072"

  odoo-pgadmin:
    hostname: odoo-pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - odoo-postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret123!
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_ENHANCED_COOKIES_ENABLED=False
      - PGADMIN_CONFIG_WTF_CSRF_ENABLED=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - odoo-network
    ports:
      - "5050:80"

volumes:
  postgres_data:
    driver: local
    name: odoo_postgres_data
  odoo_data:
    driver: local
    name: odoo_app_data
  odoo_config:
    driver: local
    name: odoo_config_data
  pgadmin_data:
    driver: local
    name: pgadmin_config_data

networks:
  odoo-network:
    driver: bridge
    name: odoo-network